version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      ignore:
          - dependency-name: "@types/node"
            versions: [">=19"]
          - dependency-name: "happy-dom"
            versions: [">=17.6.2"]
